    ColorColumn                    { bg="#685a41", },  
    Cursor                         { fg="#2c343a", bg="#ebe2cf", },  
    CursorLine                     { bg="#313a41", },  
    VertSplit                      { fg="#667783", },  
    Folded                         { fg="#6e7b85", },  
    LineNr                         { fg="#667783", },  
    NonText                        { fg="#5d6d78", },  
    FloatBorder                    { fg="#798b9a", },  
    Pmenu                          { bg="#3b464e", },  
    PmenuSel                       { fg=c.green, bg="#4e5b65", },  
    PmenuSbar                      { bg="#606f7b", },  
    PmenuThumb                     { bg="#8296a5", },  
    StatusLine                     { fg="#e7dcc4", bg="#3e4850", },  
    StatusLineNC                   { fg="#ede5d4", bg="#353f46", },  
    Visual                         { bg="#615b51", },  
    Comment                        { fg="#6e7b85", },  
    Special                        { fg="#7b8e9d" },  
