return {
  -- content here will not be touched
  -- PATCH_OPEN
  Normal = {fg = "#E7DCC4", bg = "#2C343A"},
  NormalFloat = {link = "Normal"},
  ColorColumn = {bg = "#685a41"},
  LspReferenceRead = {link = "ColorColumn"},
  LspReferenceText = {link = "ColorColumn"},
  LspReferenceWrite = {link = "ColorColumn"},
  Comment = {fg = "#6e7b85"},
  SpecialComment = {link = "Comment"},
  ["@comment"] = {link = "Comment"},
  ["@text.literal"] = {link = "Comment"},
  Conceal = {underline = true},
  Constant = {fg = "#E7DCC4"},
  ["@boolean"] = {link = "Constant"},
  ["@constant"] = {link = "Constant"},
  ["@float"] = {link = "Constant"},
  ["@number"] = {link = "Constant"},
  ["@string"] = {link = "Constant"},
  Cursor = {fg = "#2c343a", bg = "#ebe2cf"},
  CursorColumn = {bg = "grey40"},
  CursorLine = {bg = "#313a41"},
  CursorLineNr = {fg = "#E7DCC4"},
  ["@debug"] = {link = "Debug"},
  Delimiter = {fg = "#7b8e9d"},
  ["@punctuation"] = {link = "Delimiter"},
  DiagnosticError = {fg = "#E67C7F"},
  DiagnosticFloatingError = {link = "DiagnosticError"},
  DiagnosticSignError = {link = "DiagnosticError"},
  DiagnosticVirtualTextError = {link = "DiagnosticError"},
  DiagnosticHint = {fg = "#D69AB7"},
  DiagnosticFloatingHint = {link = "DiagnosticHint"},
  DiagnosticSignHint = {link = "DiagnosticHint"},
  DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
  DiagnosticInfo = {fg = "#80BCB4"},
  DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
  DiagnosticSignInfo = {link = "DiagnosticInfo"},
  DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
  DiagnosticOk = {fg = "#A9C181"},
  DiagnosticFloatingOk = {link = "DiagnosticOk"},
  DiagnosticSignOk = {link = "DiagnosticOk"},
  DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
  DiagnosticUnderlineError = {fg = "#E67C7F", underline = true},
  DiagnosticUnderlineHint = {fg = "#D69AB7", underline = true},
  DiagnosticUnderlineInfo = {fg = "#80BCB4", underline = true},
  DiagnosticUnderlineOk = {fg = "#A9C181", underline = true},
  DiagnosticUnderlineWarn = {fg = "#DDBD7F", underline = true},
  DiagnosticWarn = {fg = "#DDBD7F"},
  DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
  DiagnosticSignWarn = {link = "DiagnosticWarn"},
  DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
  DiffAdd = {fg = "#A9C181"},
  DiffChange = {fg = "#DDBD7F"},
  DiffDelete = {fg = "#E67C7F"},
  DiffText = {fg = "#80BCB4"},
  Directory = {fg = "#A9C181"},
  Error = {fg = "#E67C7F"},
  ErrorMsg = {fg = "#E67C7F"},
  FloatBorder = {fg = "#798b9a"},
  CursorLineFold = {link = "FoldColumn"},
  Folded = {fg = "#9cb4c6", bg = "#424d55"},
  FoldColumn = {link = "Folded"},
  Function = {fg = "#85C194"},
  ["@function"] = {link = "Function"},
  ["@method"] = {link = "Function"},
  Identifier = {fg = "#E7DCC4"},
  ["@field"] = {link = "Identifier"},
  ["@namespace"] = {link = "Identifier"},
  ["@parameter"] = {link = "Identifier"},
  ["@property"] = {link = "Identifier"},
  ["@text.reference"] = {link = "Identifier"},
  ["@variable"] = {link = "Identifier"},
  Ignore = {fg = "#2C343A"},
  IncSearch = {fg = "#2C343A", bg = "#D69AB7"},
  LineNr = {fg = "#667783"},
  MatchParen = {fg = "#E67C7F", bg = "#2C343A"},
  ModeMsg = {fg = "#A9C181", bold = true},
  MoreMsg = {fg = "#A9C181"},
  MsgArea = {},
  NonText = {fg = "#5d6d78"},
  Whitespace = {link = "NonText"},
  Pmenu = {bg = "#3b464e"},
  PmenuExtra = {link = "Pmenu"},
  PmenuKind = {link = "Pmenu"},
  PmenuSbar = {bg = "#606f7b"},
  PmenuSel = {bg = "#4e5b65"},
  PmenuExtraSel = {link = "PmenuSel"},
  PmenuKindSel = {link = "PmenuSel"},
  PmenuThumb = {bg = "#8296a5"},
  PreProc = {fg = "#85C194"},
  ["@constant.macro"] = {link = "PreProc"},
  ["@define"] = {link = "PreProc"},
  ["@function.macro"] = {link = "PreProc"},
  ["@include"] = {link = "PreProc"},
  ["@macro"] = {link = "PreProc"},
  ["@preproc"] = {link = "PreProc"},
  Question = {fg = "#A9C181"},
  Search = {fg = "#2C343A", bg = "#E67C7F"},
  SignColumn = {},
  Special = {fg = "#B5AA92"},
  Debug = {link = "Special"},
  SpecialChar = {link = "Special"},
  Tag = {link = "Special"},
  ["@constant.builtin"] = {link = "Special"},
  ["@constructor"] = {link = "Special"},
  SpecialKey = {fg = "#A9C181"},
  SpellBad = {undercurl = true},
  SpellCap = {undercurl = true},
  SpellLocal = {undercurl = true},
  SpellRare = {undercurl = true},
  Statement = {fg = "#A9C181"},
  ["@conditional"] = {link = "Statement"},
  ["@exception"] = {link = "Statement"},
  ["@function.builtin"] = {link = "Statement"},
  ["@keyword"] = {link = "Statement"},
  ["@label"] = {link = "Statement"},
  ["@operator"] = {link = "Statement"},
  ["@repeat"] = {link = "Statement"},
  StatusLine = {fg = "#e7dcc4", bg = "#3e4850"},
  StatusLineNC = {fg = "#ede5d4", bg = "#353f46"},
  TabLine = {fg = "#E7DCC4", bg = "#2C343A"},
  TabLineFill = {bg = "#2C343A"},
  TabLineSel = {fg = "#2C343A", bg = "#A9C181", italic = true},
  ["@tag"] = {link = "Tag"},
  TermCursor = {reverse = true},
  Title = {fg = "#E67C7F"},
  ["@text.title"] = {link = "Title"},
  Todo = {fg = "#DDBD7F"},
  ["@text.todo"] = {link = "Todo"},
  Type = {fg = "#80BCB4"},
  ["@storageclass"] = {link = "Type"},
  ["@structure"] = {link = "Type"},
  ["@type"] = {link = "Type"},
  ["@type.definition"] = {link = "Type"},
  Underlined = {underline = true},
  VertSplit = {fg = "#667783"},
  Winseparator = {link = "VertSplit"},
  Visual = {bg = "#615b51"},
  WarningMsg = {fg = "#DDBD7F"},
  WildMenu = {fg = "#2C343A", bg = "#D69AB7"},
  WinBar = {bold = true},
  WinBarNC = {link = "WinBar"},
  lCursor = {},
  TermCursorNC = {link = "lCursor"},
  ["@character"] = {},
  ["@character.special"] = {},
  ["@string.escape"] = {},
  ["@string.html"] = {fg = "#D69AB7"},
  ["@string.special"] = {},
  ["@tag.attribute.html"] = {fg = "#80BCB4"},
  ["@tag.html"] = {fg = "#85C194"},
  ["@text.underline"] = {},
  ["@text.uri"] = {},
  -- PATCH_CLOSE
  -- content here will not be touched
}
